-- =============================================================================
-- NEXHIRE AI Database Schema Migration: V01__init.sql
-- Compatible with Oracle DB (23ai/26ai), PostgreSQL, H2, and standard SQL
-- =============================================================================

-- 1. USERS
CREATE TABLE USERS (
    ID VARCHAR2(36) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    FIRST_NAME VARCHAR2(100) NOT NULL,
    LAST_NAME VARCHAR2(100) NOT NULL,
    AVATAR_URL VARCHAR2(500),
    LOCALE VARCHAR2(10) DEFAULT 'en-US' NOT NULL,
    TIMEZONE VARCHAR2(50) DEFAULT 'UTC' NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    MFA_ENABLED NUMBER(1, 0) DEFAULT 0 NOT NULL,
    MFA_SECRET VARCHAR2(100),
    EMAIL_VERIFIED_AT TIMESTAMP,
    LAST_LOGIN_AT TIMESTAMP,
    COMPANY_NAME VARCHAR2(150),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100),
    UPDATED_BY VARCHAR2(100),
    CONSTRAINT PK_USERS PRIMARY KEY (ID)
);

-- 2. USER_ROLES (ElementCollection for User)
CREATE TABLE USER_ROLES (
    USER_ID VARCHAR2(36) NOT NULL,
    ROLE VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_USER_ROLES PRIMARY KEY (USER_ID, ROLE),
    CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- 3. COMPANIES
CREATE TABLE COMPANIES (
    ID VARCHAR2(36) NOT NULL,
    NAME VARCHAR2(150) NOT NULL,
    DESCRIPTION VARCHAR2(2000),
    INDUSTRY VARCHAR2(100),
    WEBSITE_URL VARCHAR2(500),
    LOGO_URL VARCHAR2(500),
    LOCATION VARCHAR2(150),
    EMPLOYEE_COUNT NUMBER(10, 0),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100),
    UPDATED_BY VARCHAR2(100),
    CONSTRAINT PK_COMPANIES PRIMARY KEY (ID)
);

-- 4. CANDIDATE_PROFILES
CREATE TABLE CANDIDATE_PROFILES (
    ID VARCHAR2(36) NOT NULL,
    USER_ID VARCHAR2(36) NOT NULL UNIQUE,
    HEADLINE VARCHAR2(200),
    SUMMARY VARCHAR2(2000),
    PHONE VARCHAR2(30),
    LOCATION VARCHAR2(150),
    YEARS_OF_EXPERIENCE NUMBER(10, 0),
    EXPECTED_SALARY NUMBER(12, 2),
    NOTICE_PERIOD_DAYS NUMBER(10, 0),
    LINKEDIN_URL VARCHAR2(500),
    GITHUB_URL VARCHAR2(500),
    PORTFOLIO_URL VARCHAR2(500),
    RESUME_URL VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100),
    UPDATED_BY VARCHAR2(100),
    CONSTRAINT PK_CANDIDATE_PROFILES PRIMARY KEY (ID),
    CONSTRAINT FK_CANDIDATE_PROFILES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- 5. RECRUITER_PROFILES
CREATE TABLE RECRUITER_PROFILES (
    ID VARCHAR2(36) NOT NULL,
    USER_ID VARCHAR2(36) NOT NULL UNIQUE,
    COMPANY_ID VARCHAR2(36),
    TITLE VARCHAR2(150),
    DEPARTMENT VARCHAR2(100),
    PHONE VARCHAR2(30),
    LINKEDIN_URL VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100),
    UPDATED_BY VARCHAR2(100),
    CONSTRAINT PK_RECRUITER_PROFILES PRIMARY KEY (ID),
    CONSTRAINT FK_RECRUITER_PROFILES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_RECRUITER_PROFILES_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID) ON DELETE SET NULL
);

-- 6. JOBS
CREATE TABLE JOBS (
    ID VARCHAR2(36) NOT NULL,
    TITLE VARCHAR2(150) NOT NULL,
    DESCRIPTION VARCHAR2(4000) NOT NULL,
    DEPARTMENT VARCHAR2(100),
    LOCATION VARCHAR2(150),
    JOB_TYPE VARCHAR2(50),
    EXPERIENCE_LEVEL VARCHAR2(50),
    MIN_SALARY NUMBER(12, 2),
    MAX_SALARY NUMBER(12, 2),
    CURRENCY VARCHAR2(10) DEFAULT 'USD',
    STATUS VARCHAR2(20) DEFAULT 'PUBLISHED' NOT NULL,
    COMPANY_ID VARCHAR2(36),
    POSTED_BY_ID VARCHAR2(36) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100),
    UPDATED_BY VARCHAR2(100),
    CONSTRAINT PK_JOBS PRIMARY KEY (ID),
    CONSTRAINT FK_JOBS_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID) ON DELETE SET NULL,
    CONSTRAINT FK_JOBS_POSTED_BY FOREIGN KEY (POSTED_BY_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- 7. JOB_SKILLS
CREATE TABLE JOB_SKILLS (
    ID VARCHAR2(36) NOT NULL,
    JOB_ID VARCHAR2(36) NOT NULL,
    SKILL_NAME VARCHAR2(100) NOT NULL,
    IMPORTANCE VARCHAR2(30),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100),
    UPDATED_BY VARCHAR2(100),
    CONSTRAINT PK_JOB_SKILLS PRIMARY KEY (ID),
    CONSTRAINT FK_JOB_SKILLS_JOB FOREIGN KEY (JOB_ID) REFERENCES JOBS(ID) ON DELETE CASCADE
);

-- 8. APPLICATIONS
CREATE TABLE APPLICATIONS (
    ID VARCHAR2(36) NOT NULL,
    JOB_ID VARCHAR2(36) NOT NULL,
    CANDIDATE_ID VARCHAR2(36) NOT NULL,
    STATUS VARCHAR2(30) DEFAULT 'SUBMITTED' NOT NULL,
    RESUME_URL VARCHAR2(500),
    COVER_LETTER VARCHAR2(2000),
    NOTES VARCHAR2(1000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100),
    UPDATED_BY VARCHAR2(100),
    CONSTRAINT PK_APPLICATIONS PRIMARY KEY (ID),
    CONSTRAINT FK_APPLICATIONS_JOB FOREIGN KEY (JOB_ID) REFERENCES JOBS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_APPLICATIONS_CANDIDATE FOREIGN KEY (CANDIDATE_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- 9. RESUMES
CREATE TABLE RESUMES (
    ID VARCHAR2(36) NOT NULL,
    USER_ID VARCHAR2(36) NOT NULL,
    FILE_NAME VARCHAR2(200) NOT NULL,
    FILE_URL VARCHAR2(500) NOT NULL,
    FILE_SIZE NUMBER(19, 0),
    CONTENT_TYPE VARCHAR2(100),
    PARSED_DATA VARCHAR2(4000),
    PARSED NUMBER(1, 0) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100),
    UPDATED_BY VARCHAR2(100),
    CONSTRAINT PK_RESUMES PRIMARY KEY (ID),
    CONSTRAINT FK_RESUMES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- 10. WORK_EXPERIENCES
CREATE TABLE WORK_EXPERIENCES (
    ID VARCHAR2(36) NOT NULL,
    CANDIDATE_PROFILE_ID VARCHAR2(36) NOT NULL,
    COMPANY_NAME VARCHAR2(150) NOT NULL,
    TITLE VARCHAR2(150) NOT NULL,
    LOCATION VARCHAR2(150),
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    IS_CURRENT NUMBER(1, 0) DEFAULT 0 NOT NULL,
    DESCRIPTION VARCHAR2(2000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100),
    UPDATED_BY VARCHAR2(100),
    CONSTRAINT PK_WORK_EXPERIENCES PRIMARY KEY (ID),
    CONSTRAINT FK_WORK_EXP_PROFILE FOREIGN KEY (CANDIDATE_PROFILE_ID) REFERENCES CANDIDATE_PROFILES(ID) ON DELETE CASCADE
);

-- 11. EDUCATIONS
CREATE TABLE EDUCATIONS (
    ID VARCHAR2(36) NOT NULL,
    CANDIDATE_PROFILE_ID VARCHAR2(36) NOT NULL,
    INSTITUTION VARCHAR2(200) NOT NULL,
    DEGREE VARCHAR2(150) NOT NULL,
    FIELD_OF_STUDY VARCHAR2(150),
    START_DATE DATE,
    END_DATE DATE,
    GRADE VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100),
    UPDATED_BY VARCHAR2(100),
    CONSTRAINT PK_EDUCATIONS PRIMARY KEY (ID),
    CONSTRAINT FK_EDUCATIONS_PROFILE FOREIGN KEY (CANDIDATE_PROFILE_ID) REFERENCES CANDIDATE_PROFILES(ID) ON DELETE CASCADE
);

-- 12. CANDIDATE_SKILLS
CREATE TABLE CANDIDATE_SKILLS (
    ID VARCHAR2(36) NOT NULL,
    CANDIDATE_PROFILE_ID VARCHAR2(36) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    PROFICIENCY_LEVEL VARCHAR2(30),
    YEARS_OF_EXPERIENCE NUMBER(10, 0),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100),
    UPDATED_BY VARCHAR2(100),
    CONSTRAINT PK_CANDIDATE_SKILLS PRIMARY KEY (ID),
    CONSTRAINT FK_CAND_SKILLS_PROFILE FOREIGN KEY (CANDIDATE_PROFILE_ID) REFERENCES CANDIDATE_PROFILES(ID) ON DELETE CASCADE
);

-- 13. INTERVIEWS
CREATE TABLE INTERVIEWS (
    ID VARCHAR2(36) NOT NULL,
    APPLICATION_ID VARCHAR2(36) NOT NULL,
    INTERVIEWER_ID VARCHAR2(36) NOT NULL,
    SCHEDULED_AT TIMESTAMP NOT NULL,
    DURATION_MINUTES NUMBER(10, 0) DEFAULT 60,
    LOCATION VARCHAR2(200),
    MEETING_URL VARCHAR2(500),
    INTERVIEW_TYPE VARCHAR2(50),
    STATUS VARCHAR2(20) DEFAULT 'SCHEDULED' NOT NULL,
    FEEDBACK VARCHAR2(2000),
    RATING NUMBER(10, 0),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100),
    UPDATED_BY VARCHAR2(100),
    CONSTRAINT PK_INTERVIEWS PRIMARY KEY (ID),
    CONSTRAINT FK_INTERVIEWS_APP FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATIONS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_INTERVIEWS_INTERVIEWER FOREIGN KEY (INTERVIEWER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- 14. NOTIFICATIONS
CREATE TABLE NOTIFICATIONS (
    ID VARCHAR2(36) NOT NULL,
    USER_ID VARCHAR2(36) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    MESSAGE VARCHAR2(1000) NOT NULL,
    TYPE VARCHAR2(50),
    READ_AT TIMESTAMP,
    LINK VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100),
    UPDATED_BY VARCHAR2(100),
    CONSTRAINT PK_NOTIFICATIONS PRIMARY KEY (ID),
    CONSTRAINT FK_NOTIFICATIONS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- 15. EMAIL_VERIFICATION_TOKENS
CREATE TABLE EMAIL_VERIFICATION_TOKENS (
    ID VARCHAR2(36) NOT NULL,
    TOKEN VARCHAR2(128) NOT NULL UNIQUE,
    USER_ID VARCHAR2(36) NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    VERIFIED NUMBER(1, 0) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100),
    UPDATED_BY VARCHAR2(100),
    CONSTRAINT PK_EMAIL_VERIF_TOKENS PRIMARY KEY (ID),
    CONSTRAINT FK_EMAIL_TOKENS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- 16. PASSWORD_RESET_TOKENS
CREATE TABLE PASSWORD_RESET_TOKENS (
    ID VARCHAR2(36) NOT NULL,
    TOKEN VARCHAR2(128) NOT NULL UNIQUE,
    USER_ID VARCHAR2(36) NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    USED NUMBER(1, 0) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100),
    UPDATED_BY VARCHAR2(100),
    CONSTRAINT PK_PASS_RESET_TOKENS PRIMARY KEY (ID),
    CONSTRAINT FK_PASS_TOKENS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);
