-- =============================================================================
-- NEXHIRE AI Database Schema Migration: V03__job_applications_ats_upgrade.sql
-- Compatible with Oracle DB (23ai/26ai), PostgreSQL, H2, and standard SQL
-- =============================================================================

-- 1. APPLICATIONS Table Upgrades
ALTER TABLE APPLICATIONS ADD (
    ATS_SCORE NUMBER(3, 0),
    AI_RECOMMENDATION VARCHAR2(100),
    MATCHED_SKILLS VARCHAR2(2000),
    MISSING_SKILLS VARCHAR2(2000),
    EXPERIENCE_SCORE NUMBER(3, 0),
    EDUCATION_SCORE NUMBER(3, 0)
);

-- 2. JOBS Table Upgrades
ALTER TABLE JOBS ADD (
    MINIMUM_SCORE NUMBER(3, 0) DEFAULT 80
);

-- 3. INTERVIEWS Table Upgrades
ALTER TABLE INTERVIEWS ADD (
    CANDIDATE_ID VARCHAR2(36),
    MEETING_PROVIDER VARCHAR2(50),
    MEETING_ID VARCHAR2(100)
);

-- 4. Unique Constraints & Foreign Key Additions
ALTER TABLE APPLICATIONS ADD CONSTRAINT UQ_APP_CANDIDATE_JOB UNIQUE (CANDIDATE_ID, JOB_ID);
ALTER TABLE INTERVIEWS ADD CONSTRAINT FK_INTERVIEWS_CANDIDATE FOREIGN KEY (CANDIDATE_ID) REFERENCES USERS(ID) ON DELETE CASCADE;

-- 5. Performance Indexes
CREATE INDEX IX_APP_JOB_ID ON APPLICATIONS(JOB_ID);
CREATE INDEX IX_APP_CANDIDATE_ID ON APPLICATIONS(CANDIDATE_ID);
CREATE INDEX IX_APP_STATUS ON APPLICATIONS(STATUS);
CREATE INDEX IX_INTERVIEWS_APP_ID ON INTERVIEWS(APPLICATION_ID);
CREATE INDEX IX_INTERVIEWS_CANDIDATE_ID ON INTERVIEWS(CANDIDATE_ID);
