-- =============================================================================
-- NEXHIRE AI Database Schema Migration: V04__hiring_workflow_and_employment.sql
-- Compatible with Oracle DB (23ai/26ai), PostgreSQL, H2, and standard SQL
-- =============================================================================

-- 1. APPLICATIONS Table Hiring Columns
ALTER TABLE APPLICATIONS ADD (
    HIRED_AT TIMESTAMP,
    HIRED_BY VARCHAR2(36),
    OFFER_ACCEPTED_AT TIMESTAMP,
    JOINING_DATE TIMESTAMP
);

-- 2. CANDIDATE_PROFILES Employment & Availability Columns
ALTER TABLE CANDIDATE_PROFILES ADD (
    CURRENT_COMPANY VARCHAR2(150),
    CURRENT_JOB_TITLE VARCHAR2(150),
    EMPLOYMENT_STATUS VARCHAR2(50) DEFAULT 'UNEMPLOYED',
    IS_AVAILABLE NUMBER(1, 0) DEFAULT 1 NOT NULL,
    JOB_SEEKING_STATUS VARCHAR2(50) DEFAULT 'ACTIVELY_LOOKING',
    HIRED_DATE TIMESTAMP,
    CURRENT_EMPLOYER_ID VARCHAR2(36)
);

-- 3. JOBS Table Openings & Filled Position Counts
ALTER TABLE JOBS ADD (
    TOTAL_OPENINGS NUMBER(10, 0) DEFAULT 1 NOT NULL,
    FILLED_POSITIONS NUMBER(10, 0) DEFAULT 0 NOT NULL
);

-- 4. EMPLOYMENT_RECORDS Table Creation
CREATE TABLE EMPLOYMENT_RECORDS (
    ID VARCHAR2(36) NOT NULL,
    CANDIDATE_ID VARCHAR2(36) NOT NULL,
    RECRUITER_ID VARCHAR2(36) NOT NULL,
    COMPANY_ID VARCHAR2(36),
    JOB_ID VARCHAR2(36) NOT NULL,
    JOB_TITLE VARCHAR2(150) NOT NULL,
    DEPARTMENT VARCHAR2(100),
    SALARY_OFFERED NUMBER(12, 2),
    OFFER_ACCEPTED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    JOINING_DATE TIMESTAMP,
    EMPLOYMENT_STATUS VARCHAR2(50) DEFAULT 'HIRED' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100),
    UPDATED_BY VARCHAR2(100),
    CONSTRAINT PK_EMPLOYMENT_RECORDS PRIMARY KEY (ID),
    CONSTRAINT FK_EMP_REC_CANDIDATE FOREIGN KEY (CANDIDATE_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_EMP_REC_RECRUITER FOREIGN KEY (RECRUITER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_EMP_REC_JOB FOREIGN KEY (JOB_ID) REFERENCES JOBS(ID) ON DELETE CASCADE
);

-- 5. AUDIT_LOGS Table Creation (If not present)
CREATE TABLE AUDIT_LOGS (
    ID VARCHAR2(36) NOT NULL,
    USER_ID VARCHAR2(36),
    USER_EMAIL VARCHAR2(150),
    ACTION VARCHAR2(100) NOT NULL,
    RESOURCE_NAME VARCHAR2(150),
    IP_ADDRESS VARCHAR2(50),
    DETAILS VARCHAR2(2000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100),
    UPDATED_BY VARCHAR2(100),
    CONSTRAINT PK_AUDIT_LOGS PRIMARY KEY (ID)
);

-- 6. Indexes for Hiring Workflows
CREATE INDEX IX_EMP_REC_CANDIDATE ON EMPLOYMENT_RECORDS(CANDIDATE_ID);
CREATE INDEX IX_EMP_REC_JOB ON EMPLOYMENT_RECORDS(JOB_ID);
CREATE INDEX IX_EMP_REC_RECRUITER ON EMPLOYMENT_RECORDS(RECRUITER_ID);
CREATE INDEX IX_CAND_AVAILABILITY ON CANDIDATE_PROFILES(IS_AVAILABLE, EMPLOYMENT_STATUS);
CREATE INDEX IX_AUDIT_USER_ACTION ON AUDIT_LOGS(USER_ID, ACTION);
