-- =============================================================================
-- NEXHIRE AI Database Schema Migration: V05__employments_table_upgrade.sql
-- Compatible with Oracle DB (23ai/26ai), PostgreSQL, H2, and standard SQL
-- =============================================================================

-- 1. APPLICATIONS Table Salary Column
ALTER TABLE APPLICATIONS ADD (
    SALARY_OFFERED NUMBER(12, 2)
);

-- 2. CANDIDATE_PROFILES Available For Work Column
ALTER TABLE CANDIDATE_PROFILES ADD (
    AVAILABLE_FOR_WORK NUMBER(1, 0) DEFAULT 0 NOT NULL
);

-- 3. EMPLOYMENTS Table Creation
CREATE TABLE EMPLOYMENTS (
    ID VARCHAR2(36) NOT NULL,
    CANDIDATE_ID VARCHAR2(36) NOT NULL,
    RECRUITER_ID VARCHAR2(36) NOT NULL,
    COMPANY_ID VARCHAR2(36),
    APPLICATION_ID VARCHAR2(36),
    JOB_ID VARCHAR2(36) NOT NULL,
    JOB_TITLE VARCHAR2(150) NOT NULL,
    DEPARTMENT VARCHAR2(100),
    SALARY NUMBER(12, 2),
    JOINING_DATE TIMESTAMP,
    EMPLOYMENT_STATUS VARCHAR2(50) DEFAULT 'HIRED' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_EMPLOYMENTS PRIMARY KEY (ID),
    CONSTRAINT FK_EMP_CANDIDATE FOREIGN KEY (CANDIDATE_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_EMP_RECRUITER FOREIGN KEY (RECRUITER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_EMP_JOB FOREIGN KEY (JOB_ID) REFERENCES JOBS(ID) ON DELETE CASCADE
);

CREATE INDEX IX_EMP_CANDIDATE ON EMPLOYMENTS(CANDIDATE_ID);
CREATE INDEX IX_EMP_JOB ON EMPLOYMENTS(JOB_ID);
CREATE INDEX IX_EMP_RECRUITER ON EMPLOYMENTS(RECRUITER_ID);
